# Generated by Django 5.2.7 on 2025-10-21 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_importantlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='importantlocation',
            name='name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
