services:
  db:
    image: postgis/postgis:15-3.4
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    ports:
      - "5432:5432"   # change host port if conflict (e.g., "55432:5432")
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d app"]
      interval: 5s
      timeout: 5s
      retries: 20
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    environment:
      DB_NAME: app
      DB_USER: app
      DB_PASSWORD: app
      DB_HOST: db
      DB_PORT: "5432"
      DEBUG: "1"
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    command: >
      bash -c "python manage.py migrate &&
               python manage.py runserver 0.0.0.0:8000"

volumes:
  pgdata:
